import type { ApiPlan } from "./api-plan.js";

function callScript(script: string): string {
  return script.replace(/^#![^\n]*\n/, "").trimEnd();
}

function bashQuote(value: string): string {
  return `'${value.replaceAll("'", `'"'"'`)}'`;
}

export function buildApiPlanShellScript(plan: ApiPlan): string {
  if (!plan.tenantDomain) {
    throw new Error(
      `The ${plan.profile} API plan is not bound to an Auth0 tenant.`,
    );
  }
  const missing = plan.calls.filter((call) => !call.curl?.script);
  if (missing.length > 0) {
    throw new Error(
      `The ${plan.profile} API plan contains calls without validated curl scripts: ${missing
        .map((call) => call.resourceName)
        .join(", ")}.`,
    );
  }

  const calls = plan.calls
    .map(
      (
        call,
        index,
      ) => `printf '%s\\n' ${bashQuote(`Applying validated API call ${index + 1} of ${plan.calls.length}: ${call.resourceName}`)}
(
${callScript(call.curl!.script)}
)`,
    )
    .join("\n\n");

  return `#!/usr/bin/env bash
set -euo pipefail

# Generated by CheckMate Remediation Assistant.
# Profile: ${plan.profile}
# Tenant: ${plan.tenantDomain}
# Canonical audit record: api-plan.yml

${calls || 'echo "No API changes are required for this environment."'}
${calls ? '\necho "Applied and verified all validated API calls."' : ""}
`;
}
