import type { ApiPlan, ApiPlanCall } from "./api-plan.js";
import {
  CURL_API_SHELL_RUNTIME,
  curlApiReadEndpoint,
  curlApiRequiredScopes,
} from "./curl-api-script.js";
import { assertSupportedApiPlanCall } from "../auth0/writable-patch.js";

function bashQuote(value: string): string {
  return `'${value.replaceAll("'", `'"'"'`)}'`;
}

function base64Json(value: unknown): string {
  return Buffer.from(JSON.stringify(value), "utf8").toString("base64");
}

function environmentVariables(profile: "dev" | "prod"): {
  domain: string;
  clientId: string;
  clientSecret: string;
} {
  const prefix = `AUTH0CHECKMATE_${profile.toUpperCase()}`;
  return {
    domain: `${prefix}_DOMAIN`,
    clientId: `${prefix}_CLIENT_ID`,
    clientSecret: `${prefix}_CLIENT_SECRET`,
  };
}

function requiredScopes(calls: readonly ApiPlanCall[]): string {
  const result = new Set<string>();
  for (const call of calls) {
    for (const scope of curlApiRequiredScopes(call)) result.add(scope);
  }
  return [...result].join(" ");
}

function invocation(call: ApiPlanCall, index: number, total: number): string {
  if (!call.validatedRequestSha256) {
    throw new Error(
      `The validated PATCH request digest is missing for ${call.resourceName}.`,
    );
  }
  assertSupportedApiPlanCall(call);
  return `apply_validated_call \\
  ${bashQuote(String(index + 1))} \\
  ${bashQuote(String(total))} \\
  ${bashQuote(call.id)} \\
  ${bashQuote(call.resourceName)} \\
  ${bashQuote(call.resourceType)} \\
  ${bashQuote(call.endpoint)} \\
  ${bashQuote(curlApiReadEndpoint(call))} \\
  ${bashQuote(call.bodyStrategy)} \\
  ${bashQuote(call.validatedRequestSha256)} \\
  ${bashQuote(base64Json(call.body))} \\
  ${bashQuote(base64Json(call.preconditions))}`;
}

export function buildConsolidatedApiPlanShell(plan: ApiPlan): string {
  if (!plan.tenantDomain) {
    throw new Error(
      `The ${plan.profile} API plan is not bound to an Auth0 tenant.`,
    );
  }
  if (plan.calls.length === 0) {
    return `#!/usr/bin/env bash
set -euo pipefail

# Generated by CheckMate Remediation Assistant.
# Profile: ${plan.profile}
# Tenant: ${plan.tenantDomain}
# Canonical audit record: api-plan.yml

echo "No API changes are required for this environment."
`;
  }

  const variables = environmentVariables(plan.profile);
  const calls = plan.calls
    .map((call, index) => invocation(call, index, plan.calls.length))
    .join("\n\n");

  return `#!/usr/bin/env bash
set -euo pipefail

# Generated by CheckMate Remediation Assistant.
# Profile: ${plan.profile}
# Tenant: ${plan.tenantDomain}
# Canonical audit record: api-plan.yml
# Uses one authenticated session for all validated PATCH calls.

umask 077
for command in curl node; do
  command -v "\${command}" >/dev/null 2>&1 || {
    echo "Missing required command: \${command}" >&2
    exit 1
  }
done

EXPECTED_DOMAIN=${bashQuote(plan.tenantDomain)}
DOMAIN="\${${variables.domain}:?Set ${variables.domain}}"
CLIENT_ID="\${${variables.clientId}:?Set ${variables.clientId}}"
CLIENT_SECRET="\${${variables.clientSecret}:?Set ${variables.clientSecret}}"
export -n CLIENT_ID CLIENT_SECRET 2>/dev/null || true
unset ${variables.clientId} ${variables.clientSecret}
if [[ "\${DOMAIN}" != "\${EXPECTED_DOMAIN}" ]]; then
  echo "Execution stopped: ${variables.domain} must exactly match the validated tenant \${EXPECTED_DOMAIN}." >&2
  exit 1
fi

export BASE_URL="https://\${DOMAIN}"
export SCOPES=${bashQuote(requiredScopes(plan.calls))}
WORK_DIRECTORY="$(mktemp -d "\${TMPDIR:-/tmp}/checkmate-curl.XXXXXX")"
TOKEN_PAYLOAD_FILE="\${WORK_DIRECTORY}/token-request.json"
AUTH_HEADER_FILE="\${WORK_DIRECTORY}/authorization-header"
BEFORE_FILE="\${WORK_DIRECTORY}/before.json"
PATCH_RESPONSE_FILE="\${WORK_DIRECTORY}/patch-response.json"
PATCH_HEADERS_FILE="\${WORK_DIRECTORY}/patch-headers.txt"
cleanup() {
  rm -f "\${TOKEN_PAYLOAD_FILE}" "\${AUTH_HEADER_FILE}" "\${BEFORE_FILE}" \\
    "\${PATCH_RESPONSE_FILE}" "\${PATCH_HEADERS_FILE}"
  rmdir "\${WORK_DIRECTORY}" 2>/dev/null || true
}
trap cleanup EXIT
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM
export CHECKMATE_BEFORE_FILE="\${BEFORE_FILE}"

printf '%s\\0%s\\0%s\\0%s\\0' \\
  "\${CLIENT_ID}" "\${CLIENT_SECRET}" "\${BASE_URL}/api/v2/" "\${SCOPES}" |
  node -e ${bashQuote(CURL_API_SHELL_RUNTIME.tokenPayloadScript)} > "\${TOKEN_PAYLOAD_FILE}"
unset CLIENT_SECRET

TOKEN_RESPONSE="$(
  curl --fail-with-body --silent --show-error \\
    --retry 5 --retry-delay 1 --retry-max-time 150 \\
    --request POST "\${BASE_URL}/oauth/token" \\
    --header 'content-type: application/json' \\
    --data-binary "@\${TOKEN_PAYLOAD_FILE}"
)"
export -n TOKEN_RESPONSE 2>/dev/null || true
ACCESS_TOKEN="$(printf '%s' "\${TOKEN_RESPONSE}" | node -e ${bashQuote(CURL_API_SHELL_RUNTIME.tokenParserScript)})"
export -n ACCESS_TOKEN 2>/dev/null || true
printf 'Authorization: Bearer %s\\n' "\${ACCESS_TOKEN}" > "\${AUTH_HEADER_FILE}"
unset ACCESS_TOKEN TOKEN_RESPONSE CLIENT_ID

read_resource() {
  curl --fail-with-body --silent --show-error \\
    --retry 5 --retry-delay 1 --retry-max-time 150 \\
    "\${BASE_URL}\${CHECKMATE_READ_ENDPOINT}" \\
    --header "@\${AUTH_HEADER_FILE}"
}

apply_validated_call() {
  local call_number="$1"
  local call_count="$2"
  local call_id="$3"
  export CHECKMATE_RESOURCE_NAME="$4"
  export CHECKMATE_RESOURCE_TYPE="$5"
  export CHECKMATE_ENDPOINT="$6"
  export CHECKMATE_READ_ENDPOINT="$7"
  export CHECKMATE_BODY_STRATEGY="$8"
  export CHECKMATE_EXPECTED_REQUEST_SHA256="$9"
  export CHECKMATE_PLANNED_B64="\${10}"
  export CHECKMATE_PRECONDITIONS_B64="\${11}"

  printf '%s\\n' "Applying validated API call \${call_number} of \${call_count}: \${CHECKMATE_RESOURCE_NAME}"
  local live request state patch_body patch_attempt patch_status patch_error
  local patch_delay verified patch_correlation_id
  live="$(read_resource)"
  printf '%s' "\${live}" > "\${BEFORE_FILE}"
  request="$(printf '%s' "\${live}" | node -e ${bashQuote(CURL_API_SHELL_RUNTIME.requestBuilderScript)})"
  state="$(printf '%s' "\${request}" | node -e ${bashQuote(CURL_API_SHELL_RUNTIME.responseFieldScript)} state)"
  if [[ "\${state}" == "already_applied" ]]; then
    echo "No change needed: \${CHECKMATE_RESOURCE_NAME} already has the planned settings."
    return 0
  fi

  patch_body="$(printf '%s' "\${request}" | node -e ${bashQuote(CURL_API_SHELL_RUNTIME.responseFieldScript)} body)"
  patch_attempt=0
  patch_correlation_id="checkmate-curl-\${call_id}-$(date +%s)"
  while true; do
    : > "\${PATCH_RESPONSE_FILE}"
    : > "\${PATCH_HEADERS_FILE}"
    if ! patch_status="$(
      printf '%s' "\${patch_body}" |
        curl --silent --show-error \\
          --output "\${PATCH_RESPONSE_FILE}" \\
          --dump-header "\${PATCH_HEADERS_FILE}" \\
          --write-out '%{http_code}' \\
          --request PATCH "\${BASE_URL}\${CHECKMATE_ENDPOINT}" \\
          --header "@\${AUTH_HEADER_FILE}" \\
          --header 'content-type: application/json' \\
          --header "x-correlation-id: \${patch_correlation_id}" \\
          --data-binary @-
    )"; then
      echo "Auth0 PATCH request failed before a response was received." >&2
      return 1
    fi

    case "\${patch_status}" in
      2??)
        break
        ;;
      429)
        if (( patch_attempt >= 5 )); then
          patch_error="$(node -e ${bashQuote(CURL_API_SHELL_RUNTIME.patchErrorScript)} "\${PATCH_RESPONSE_FILE}")"
          echo "Auth0 PATCH remained rate limited after 5 controlled retries\${patch_error:+: \${patch_error}}." >&2
          return 1
        fi
        patch_delay="$(node -e ${bashQuote(CURL_API_SHELL_RUNTIME.rateLimitDelayScript)} "\${PATCH_HEADERS_FILE}" "\${patch_attempt}")"
        echo "Auth0 rate limit reached for \${CHECKMATE_RESOURCE_NAME}; waiting \${patch_delay}s before a safe re-check (retry $((patch_attempt + 1))/5)." >&2
        sleep "\${patch_delay}"

        live="$(read_resource)"
        request="$(printf '%s' "\${live}" | node -e ${bashQuote(CURL_API_SHELL_RUNTIME.requestBuilderScript)})"
        state="$(printf '%s' "\${request}" | node -e ${bashQuote(CURL_API_SHELL_RUNTIME.responseFieldScript)} state)"
        if [[ "\${state}" == "already_applied" ]]; then
          printf '%s' "\${live}" | node -e ${bashQuote(CURL_API_SHELL_RUNTIME.verifyScript)}
          echo "Applied and verified: \${CHECKMATE_RESOURCE_NAME}"
          return 0
        fi
        patch_body="$(printf '%s' "\${request}" | node -e ${bashQuote(CURL_API_SHELL_RUNTIME.responseFieldScript)} body)"
        patch_attempt=$((patch_attempt + 1))
        ;;
      *)
        patch_error="$(node -e ${bashQuote(CURL_API_SHELL_RUNTIME.patchErrorScript)} "\${PATCH_RESPONSE_FILE}")"
        echo "Auth0 PATCH failed with status \${patch_status}\${patch_error:+: \${patch_error}}." >&2
        return 1
        ;;
    esac
  done

  verified="$(read_resource)"
  printf '%s' "\${verified}" | node -e ${bashQuote(CURL_API_SHELL_RUNTIME.verifyScript)}
  echo "Applied and verified: \${CHECKMATE_RESOURCE_NAME}"
}

${calls}

echo "Applied and verified all validated API calls."
`;
}
