import { createHash } from "node:crypto";
import path from "node:path";
import type { ApiPlan, ApiPlanCall } from "./api-plan.js";

const AUTH0_TERRAFORM_PROVIDER_VERSION = "~> 1.51.0";

function hclString(value: string): string {
  return JSON.stringify(value);
}

function hclValue(value: unknown): string {
  if (
    value === null ||
    typeof value === "boolean" ||
    typeof value === "number"
  ) {
    return JSON.stringify(value);
  }
  if (typeof value === "string") return hclString(value);
  if (Array.isArray(value)) {
    return `[${value.map((item) => hclValue(item)).join(", ")}]`;
  }
  throw new Error("Terraform output contains an unsupported value type.");
}

function valueAt(source: unknown, dottedPath: string): unknown {
  let current = source;
  for (const segment of dottedPath.split(".")) {
    if (
      current === null ||
      typeof current !== "object" ||
      Array.isArray(current)
    ) {
      return undefined;
    }
    current = (current as Record<string, unknown>)[segment];
  }
  return current;
}

function terraformLabel(call: ApiPlanCall): string {
  const readable = call.resourceName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 35);
  const digest = createHash("sha256")
    .update(`${call.resourceType}:${call.resourceId}`)
    .digest("hex")
    .slice(0, 8);
  return `${readable || "resource"}_${digest}`;
}

function dataSources(plan: ApiPlan): string[] {
  const blocks: string[] = [];
  const connections = new Map<string, ApiPlanCall>();
  const clients = new Map<string, ApiPlanCall>();
  for (const call of plan.calls) {
    if (call.resourceType === "connection") {
      connections.set(call.resourceId, call);
    }
    if (call.resourceType === "client") {
      clients.set(call.resourceId, call);
    }
  }
  for (const call of connections.values()) {
    blocks.push(`data "auth0_connection" "${terraformLabel(call)}" {
  connection_id        = ${hclString(call.resourceId)}
  skip_enabled_clients = true
}`);
  }
  for (const call of clients.values()) {
    blocks.push(`data "auth0_client" "${terraformLabel(call)}" {
  client_id = ${hclString(call.resourceId)}
}`);
  }
  if (plan.calls.some((call) => call.resourceType === "attack_protection")) {
    blocks.push(`data "auth0_attack_protection" "current" {}`);
  }
  return blocks;
}

function changeObject(call: ApiPlanCall): string {
  const changes = call.preconditions.map((precondition) => {
    const target = valueAt(call.body, precondition.path);
    if (target === undefined) {
      throw new Error(
        `Terraform output is missing a target for ${precondition.path}.`,
      );
    }
    return `          {
            path     = ${hclString(precondition.path)}
            current  = ${hclValue(precondition.expectedValue)}
            proposed = ${hclValue(target)}
          }`;
  });
  return `      {
        id            = ${hclString(call.id)}
        method        = ${hclString(call.method)}
        endpoint      = ${hclString(call.endpoint)}
        resource_type = ${hclString(call.resourceType)}
        resource_id   = ${hclString(call.resourceId)}
        resource_name = ${hclString(call.resourceName)}
        changes = [
${changes.join(",\n")}
        ]
      }`;
}

export function buildTerraformReviewConfiguration(plan: ApiPlan): string {
  const sources = dataSources(plan);
  const calls = plan.calls.map(changeObject);
  return `# Generated by CheckMate Remediation Assistant.
# Review-only Terraform representation. The hashed API plan is the execution artifact.
# Existing Auth0 resources are read through the official Auth0 provider; no resource is applied by this file.

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    auth0 = {
      source  = "auth0/auth0"
      version = "${AUTH0_TERRAFORM_PROVIDER_VERSION}"
    }
  }
}

provider "auth0" {}

${sources.join("\n\n")}

locals {
  checkmate_remediation = {
    schema_version = 1
    profile        = ${hclString(plan.profile)}
    source_report  = ${hclString(path.basename(plan.sourceReport))}
    generated_at   = ${hclString(plan.generatedAt)}
    api_calls = [
${calls.join(",\n")}
    ]
    unchanged_action_ids         = ${hclValue(plan.unchangedActionIds)}
    already_compliant_action_ids = ${hclValue(plan.alreadyCompliantActionIds)}
  }
}

output "checkmate_remediation" {
  description = "Reviewed CheckMate remediation changes for ${plan.profile}."
  value       = local.checkmate_remediation
}
`;
}
